vim.g.mapleader = ' '
vim.keymap.set('n', '<leader>pv', vim.cmd.Ex)
vim.keymap.set('n', '<leader>wq', ':%s/\\s\\+$//e<CR><CR> :wq<CR>')
vim.keymap.set('n', '<leader>q', ':q<CR>')
vim.keymap.set('n', '<leader>w', ':%s/\\s\\+$//e<CR> :w<CR>')
vim.keymap.set('n', '<leader>vr', ':w<CR> :so<CR>')
vim.keymap.set('n', '<leader>tn', ':tabnew<CR>')
vim.keymap.set('n', '<leader>te', ':tabe')
vim.keymap.set('n', '<leader>tm', ':tabmove')
vim.keymap.set('n', '<leader>tc', ':tabclose<CR>')
vim.keymap.set('n', '<leader>to', ':tabonly<CR>')
vim.keymap.set('n', '<C-h>', ':tabprevious<CR>')
vim.keymap.set('n', '<C-l>', ':tabnext<CR>')
vim.keymap.set('n', '<C-_>', ':CommentToggle<CR>')
vim.keymap.set('x', '<C-_>', ':CommentToggle<CR>')
vim.keymap.set('n', '<leader>mkdp', ':MarkdownPreview<CR>')
vim.keymap.set('n', '<F4>', ':NERDTreeToggle<CR>')
-- vim.keymap.set('n', 'tab', >>)
